# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: Maven@3
  inputs:
    mavenPomFile: 'billing/pom.xml'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.8'
    mavenVersionOption: 'Default'
    mavenOptions: '-Xmx3072m'
    mavenAuthenticateFeed: false
    effectivePomSkip: false
    sonarQubeRunAnalysis: false
- task: Docker@2
  inputs:
    containerRegistry: 'DockerHub'
    repository: 'henda24/billing_app_backend'
    command: 'buildAndPush'
    Dockerfile: 'billing/Dockerfile'
    buildContext: 'billing/'

- task: Docker@2
  inputs:
    containerRegistry: 'DockerHub'
    repository: 'henda24/billing_app_front'
    command: 'buildAndPush'
    Dockerfile: 'angularWorkSpace/Dockerfile'
    buildContext: 'angularWorkSpace/'

- task: SendTelegramNotification@0
  inputs:
    botToken: '$(tokenBotTelegram)'
    chats: '$(idChat)'
    teamUrl: true
    message: 'Pruebas, Pipeline'
    releaseName: true
    releaseRequestedFor: true
  
